extends Node

signal game_state_changed(new_state: int)
signal player_died(reason: String)
signal player_leveled_up(new_level: int)
signal xp_gained(amount: int)
signal enemy_killed(enemy_id: String, position: Vector2)
signal damage_dealt(source: Node, target: Node, amount: float, damage_type: int)
signal health_changed(current_hp: float, max_hp: float)
signal stamina_changed(current: float, max_value: float)
signal pickup_collected(pickup_type: String, amount: int)
signal gold_changed(current_gold: int)
signal room_entered(room_id: String, room_type: String)
signal room_cleared(room_id: String)
signal ore_changed(current_ore: int)
signal narrative_choice(chapter_id: String, segment_id: String, choice_id: String)
signal route_changed(alignment: float)
signal frostbite_changed(value: float)
signal void_corruption_changed(value: float)
signal memory_fragment_found(fragment_id: String)
signal accessory_acquired(accessory_id: String)
signal achievement_unlocked(achievement_id: String, title: String)
signal ending_unlocked(ending_id: String)
signal codex_unlocked(category: String, entry_id: String)
signal game_paused(paused: bool)
signal settings_changed(settings: Dictionary)
